services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: AllieLover 
      POSTGRES_PASSWORD: Allie4l1f3! 
      POSTGRES_DB: postgres 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

